### ISSUE TITLE
Flow elements are not preserved during manifest xml save

### ISSUE THREAD

**Issue by GatorQue** [GatorQue/git-reflow#10]
Need to add the ability to save the `<flow>` elements during a manifest save operation. Internally, it should be possible to detect when the `<flow>` elements should be saved in `<project>` element or the `<remote>` element by comparing the project.flow and project.remote.flow values. If they are identical, then the `<flow>` element belongs at the `<remote>` level. If both exist, but are not identical, then it belongs in both the `<project>` and `<remote>` elements (project override case). If project.remote.flow doesn't exist, then it should only be at the `<project>` level. The above should only be done if peg to revision is not enabled.

**Comment by GatorQue** [comment]
Now implemented, see commit hash: 1169b5f220ea5e74954d8e1950fa9ab8995b27e6.

**Comment by smipi1** [comment]
@GatorQue,

Have a look at the python tool written to modify manifests in the BSB002
platform project. It will be in build/bsb002/tools/manifest or make/tools.
It preserves the xml structure as well as possible by using lxml.
