### ISSUE TITLE
Add flow subcmd: Filter based on flow specification

### ISSUE THREAD

**Issue by smipi1** [GatorQue/git-reflow#5]

**Comment by GatorQue** [comment]
That proved to be harder than I initially thought. Some of the biggest challenges were trying to get repo not to complain about any "-xyz" arguments that show up in the arguments section of:
repo flow <options> <command> <arguments>
I eventually had to override the OptionParser property and set the disable interspersed args property to force OptionParser to stop processing arguments when it reaches <command>. Then I just readd flow to the list of arguments provided and call GitCommand to perform the git command in each project directory.  Its been delivered. Please give it a test and let me know what you think. I'm sure there will be some things we will need to tweak, but hopefully it will work overall.
