### ISSUE TITLE
Gitflow in .git/config is not updated on repo sync

### ISSUE THREAD

**Issue by GatorQue** [GatorQue/git-reflow#7]
When manifest.xml file is edited and a <flow/> element is added followed by a repo sync, the .git/config isn't updated with the necessary gitflow configuration elements. This issue needs to determine where this can be detected and make a call to self.flow.SetConfig(config,self.remote.name) to make this happen (where self == Project class).

**Comment by smipi1** [comment]
@GatorQue ,

An alternative (maybe simpler for now), is to implement a `repo flow init`. `git flow` users are used to first calling `init`. We can also detect an absent or incomplete init, and apply it the first time a `repo flow` sub command is called.

**Comment by GatorQue** [comment]
That is a good suggestion, we can loop through each project on an init command and perform the Flow.SetConfig step to pre-initialize each of them.

**Comment by GatorQue** [comment]
Implemented by adding a repo flow init command that performs the project.flow.SetConfig call followed by a direct git flow init on each project folder (we may want to consider doing the steps provided by git flow init directly instead). See commit hash 26187f87a

**Comment by GatorQue** [comment]
Implemented check for develop and master branches with an error to the user if they are missing to run repo flow init. This was done in commit hash 4d3e164 and e8b5606.

**Comment by smipi1** [comment]
That would be more efficient, but it may break for later versions of git
flow. What do you think?

**Comment by GatorQue** [comment]
The code still calls git flow init, but it attempts to perform the creation of local branches for the develop and master branches before calling git flow init, hopefully causing it to be a no-op. Is this sufficient for future compatibility?

**Comment by smipi1** [comment]
Should be then. Have you benchmarked the two options?
